apiVersion: v1
kind: Secret

metadata:
  name: mariadb-secret
  namespace: wordpress

type: Opaque

stringData:
  MARIADB_ROOT_PASSWORD: RootPassword123!
  MARIADB_DATABASE: wordpress
  MARIADB_USER: wordpress
  MARIADB_PASSWORD: WordpressPassword123!