apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Namespace only 
  #- ../../apps/namespace.yaml

  # Create Secret for MariaDB
  #- ../../apps/shared/base/rbac.yaml
  #- ../../apps/shared/base/generate-secret-job.yaml

  # MariaDB-Database
  #- ../../apps/mariadb/base/service.yaml
  #- ../../apps/mariadb/base/statefulset.yaml

  # WordPress-App
  #- ../../apps/wordpress/base/pvc.yaml
  #- ../../apps/wordpress/base/service.yaml
  #- ../../apps/wordpress/base/deployment.yaml

  #- ../../apps/mariadb/base/secret.yaml
