apiVersion: v1
kind: ServiceAccount

metadata:
  name: secret-generator
  namespace: wordpress
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: secret-generator
  namespace: wordpress

rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs:
  - get
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: secret-generator
  namespace: wordpress

subjects:
- kind: ServiceAccount
  name: secret-generator

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-generator