apiVersion: batch/v1
kind: Job

metadata:
  name: generate-mariadb-secret
  namespace: wordpress

spec:
  template:
    spec:
      restartPolicy: Never

      serviceAccountName: secret-generator

      containers:
      - name: secret-generator

        image: bitnami/kubectl:latest

        command:
        - /bin/sh
        - -c
        - |
          if kubectl get secret mariadb-secret -n wordpress >/dev/null 2>&1; then
            echo "Secret already exists"
            exit 0
          fi

          PASSWORD=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 32)

          kubectl create secret generic mariadb-secret \
            -n wordpress \
            --from-literal=MARIADB_ROOT_PASSWORD="$PASSWORD" \
            --from-literal=MARIADB_DATABASE="wordpress" \
            --from-literal=MARIADB_USER="wordpress" \
            --from-literal=MARIADB_PASSWORD="$PASSWORD"